// Code generated by "stringer --type=WorkoutType"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Duration-1]
	_ = x[Count-2]
}

const _WorkoutType_name = "DurationCount"

var _WorkoutType_index = [...]uint8{0, 8, 13}

func (i WorkoutType) String() string {
	i -= 1
	if i < 0 || i >= WorkoutType(len(_WorkoutType_index)-1) {
		return "WorkoutType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WorkoutType_name[_WorkoutType_index[i]:_WorkoutType_index[i+1]]
}
