// Code generated by "stringer -type=WorkoutStatus"; DO NOT EDIT.

package terminal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorkoutStatus_Break-0]
	_ = x[WorkoutStatus_Work-1]
	_ = x[WorkoutStatus_Fin-2]
}

const _WorkoutStatus_name = "WorkoutStatus_BreakWorkoutStatus_WorkWorkoutStatus_Fin"

var _WorkoutStatus_index = [...]uint8{0, 19, 37, 54}

func (i WorkoutStatus) String() string {
	if i < 0 || i >= WorkoutStatus(len(_WorkoutStatus_index)-1) {
		return "WorkoutStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WorkoutStatus_name[_WorkoutStatus_index[i]:_WorkoutStatus_index[i+1]]
}
