// Code generated by "stringer -type=TodoStatus -linecomment"; DO NOT EDIT.

package todo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TodoStatus_Default-0]
	_ = x[TodoStatus_Completed-1]
	_ = x[TodoStatus_Closed-2]
}

const _TodoStatus_name = "defaultcompletedclosed"

var _TodoStatus_index = [...]uint8{0, 7, 16, 22}

func (i TodoStatus) String() string {
	if i < 0 || i >= TodoStatus(len(_TodoStatus_index)-1) {
		return "TodoStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TodoStatus_name[_TodoStatus_index[i]:_TodoStatus_index[i+1]]
}
