// Code generated by "stringer -type=ReplaceProbe -linecomment"; DO NOT EDIT.

package file

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReplaceProbe_Service-0]
	_ = x[ReplaceProbe_Message-1]
}

const _ReplaceProbe_name = "api placemessage place"

var _ReplaceProbe_index = [...]uint8{0, 9, 22}

func (i ReplaceProbe) String() string {
	if i < 0 || i >= ReplaceProbe(len(_ReplaceProbe_index)-1) {
		return "ReplaceProbe(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplaceProbe_name[_ReplaceProbe_index[i]:_ReplaceProbe_index[i+1]]
}
